In [2]:
# 4) Replace negative value with zero in numpy array using replace 

In [1]:
import numpy as np

In [9]:


arr = np.array([[6, -8, 73, -110],
                [5, -8, 0, 94]])

print("Original Array:")
print(arr)

arr[arr < 0] = 0

print("\nArray after replacing negative values with 0:")
print(arr)

Original Array:
[[   6   -8   73 -110]
 [   5   -8    0   94]]

Array after replacing negative values with 0:
[[ 6  0 73  0]
 [ 5  0  0 94]]
