In [1]:
# 3) Replace NaN values with average of columns

In [2]:
import numpy as np

In [6]:


arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])

print("Original Array:")
print(arr)

# Column-wise mean ignoring NaN
col_mean = np.nanmean(arr, axis=0)

# Find NaN positions
inds = np.where(np.isnan(arr))

# Replace NaN with corresponding column mean
arr[inds] = np.take(col_mean, inds[1])

print("\nArray after replacing NaN with column average:")
print(arr)

Original Array:
[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

Array after replacing NaN with column average:
[[   6.   -8.   73. -110.]
 [   6.   -8.    0.   94.]]
