In [ ]:
# 1) Replace Nan with 0 and Interchangea 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]]

In [1]:
import numpy as np

In [8]:

arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])

print("Original Array:")
print(arr)

res = np.nan_to_num(arr)
print("\nAfter Replacing NaN with 0:")
print(res)

print("\nAfter Interchanging Rows and Columns:")
print(np.transpose(res))

Original Array:
[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

After Replacing NaN with 0:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

After Interchanging Rows and Columns:
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]
