In [1]:
# 2) Move axes of 3D array to new positions 

In [2]:
import numpy as np

In [3]:


arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Original Shape:", arr.shape)
print(arr)

# Move axis 0 to position 2
res = np.moveaxis(arr, 0, 2)

print("\nNew Shape:", res.shape)
print(res)

Original Shape: (2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

New Shape: (2, 2, 2)
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
