In [1]:
# > Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]] 

In [2]:
import numpy as np

In [3]:
import numpy as np

arr = np.array([[23, 56, 78, 93],
                [71, 82, 13, 24]])

print("Original Array:")
print(arr)

# Iterate through rows and columns
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i][j] % 2 != 0:   # Check if odd
            arr[i][j] = -1

print("\nModified Array:")
print(arr)

Original Array:
[[23 56 78 93]
 [71 82 13 24]]

Modified Array:
[[-1 56 78 -1]
 [-1 82 -1 24]]
