In [ ]:
#  > Convert a Python list into a NumPy array

In [1]:
import numpy as np

In [4]:
lst=[10,20,30,40,50]
arr=np.array(lst)
print(arr,type(arr))

[10 20 30 40 50] <class 'numpy.ndarray'>


In [ ]:
# Reverse a 1D NumPy array 

In [6]:
reversed_array=arr[-1::-1]
print(reversed_array)

[50 40 30 20 10]


In [ ]:
# > Create a 4×4×3 array and extract value 
# at its second set, first row and last column 

In [7]:

# Create a 4×4×3 array
arr = np.arange(48).reshape(4, 4, 3)

print(arr)

# Extract value at:
# second set -> index 1
# first row  -> index 0
# last column -> index 2
value = arr[1, 0, 2]

print("Required value:", value)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
Required value: 14
