In [ ]:
# > Create a 4×4 and Extract Odd Rows and Even Columns 

In [1]:
import numpy as np

In [2]:
import numpy as np

# Create a 4×4 array
arr = np.arange(1, 17).reshape(4, 4)

print("Original Array:")
print(arr)

# Extract odd rows and even columns
result = arr[::2, 1::2]

print("\nOdd Rows and Even Columns:")
print(result)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Odd Rows and Even Columns:
[[ 2  4]
 [10 12]]


In [4]:
# > Slice the first two rows and first two columns of second set from a 4×4×3 array

# Create a 4×4 array
arr = np.arange(1, 49).reshape(4, 4,3)

print("Original Array:")
print(arr)

result = arr[1, 0:2, 0:2]

print("\nRequired Slice:")
print(result)

Original Array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]

Required Slice:
[[13 14]
 [16 17]]
