In [1]:
# 5) Iterate 3D array using for loop and nditer 

In [3]:
import numpy as np 


arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],

    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

# Print original 3D array
print("3D Array:")
print(arr)

# Iterate 3D array using nested for loops
print("\nIterating using for loops:")

for i in arr:              # Iterate through 2D arrays
    for j in i:            # Iterate through rows
        for k in j:        # Iterate through elements
            print(k)

# Iterate 3D array using nditer()

print("\nIterating using nditer():")

for x in np.nditer(arr):
    print(x)


3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Iterating using for loops:
1
2
3
4
5
6
7
8
9
10
11
12

Iterating using nditer():
1
2
3
4
5
6
7
8
9
10
11
12
