In [2]:
# 4) Practice operations like Get the maximum value from given array 
# Get the minimum value from given array 
# Find the number of rows and columns of a given array using NumPy 
# Select the elements from a given array (each element and specific element) Find the sum of values in a 2D array using for loop Adding, Subtracting, multiplying, dividing arrays in Numpy 

In [1]:
import numpy as np


In [8]:
# Create a 2D NumPy array
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
# Print original array
print("Original Array:")
print(arr)

Original Array:
[[10 20 30]
 [40 50 60]]


In [9]:
# Get maximum value from array
print("\nMaximum Value:")
print(arr.max())

# Get minimum value from array
print("\nMinimum Value:")
print(arr.min())


Maximum Value:
60

Minimum Value:
10


In [10]:
# Find number of rows and columns
rows = arr.shape[0]
cols = arr.shape[1]

print("\nNumber of Rows:", rows)
print("Number of Columns:", cols)


Number of Rows: 2
Number of Columns: 3


In [11]:
# Select all elements one by one
print("\nAll Elements:")

for i in range(rows):
    for j in range(cols):
        print(arr[i][j])



All Elements:
10
20
30
40
50
60


In [12]:
# Select specific element
print("\nSpecific Element at row 1 column 2:")
print(arr[1][2])


Specific Element at row 1 column 2:
60


In [13]:
# Find sum of all elements using for loop
total = 0

for i in range(rows):
    for j in range(cols):
        total += arr[i][j]

print("\nSum of All Elements:")
print(total)



Sum of All Elements:
210


In [14]:
# Create another array for arithmetic operations
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("\nSecond Array:")
print(arr2)



Second Array:
[[1 2 3]
 [4 5 6]]


In [15]:
# Addition of arrays
print("\nAddition:")
print(arr + arr2)



Addition:
[[11 22 33]
 [44 55 66]]


In [16]:
# Subtraction of arrays
print("\nSubtraction:")
print(arr - arr2)



Subtraction:
[[ 9 18 27]
 [36 45 54]]


In [17]:
# Multiplication of arrays
print("\nMultiplication:")
print(arr * arr2)



Multiplication:
[[ 10  40  90]
 [160 250 360]]


In [18]:
# Division of arrays
print("\nDivision:")
print(arr / arr2)


Division:
[[10. 10. 10.]
 [10. 10. 10.]]
