In [ ]:
# 2) Flatten a 2d numpy array into 1d array 

In [1]:
import numpy as np

In [3]:


# Create a 2D array
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

# Print original array
print("Original Array:")
print(arr)

# Convert 2D array into 1D array
flat_arr = arr.flatten()

# Print flattened array
print("Flattened Array:")
print(flat_arr)

Original Array:
[[10 20 30]
 [40 50 60]]
Flattened Array:
[10 20 30 40 50 60]
