In [1]:
# 6) Study the following program import numpy as np 
# create a numpy 1d-arrays arr1 = np.array([3, 4]) arr2 = np.array([1, 0]) 
# find average of NumPy arrays avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg) -> 
# Calculate average mean median mode values of two NumPy 2d-arrays

In [2]:
import numpy as np

In [ ]:
# Create first array
arr1 = np.array([3, 4])

# Create second array
arr2 = np.array([1, 0])

# Print first array
print(arr1)

# Print second array
print(arr2)

# Calculate average of corresponding elements
avg = (arr1 + arr2) / 2

# Print average array
print("Average of NumPy arrays:\n", avg)

[3 4]
[1 0]
Average of NumPy arrays:
 [2. 2.]


In [5]:
import numpy as np
from scipy import stats   # Import stats module for mode

# Create first 2D array
arr1 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

# Create second 2D array
arr2 = np.array([
    [15, 25, 35],
    [45, 55, 65]
])

# Print arrays
print("First Array:")
print(arr1)

print("\nSecond Array:")
print(arr2)

First Array:
[[10 20 30]
 [40 50 60]]

Second Array:
[[15 25 35]
 [45 55 65]]


In [6]:
# Calculate Mean (Average)
print("\nMean of First Array:")
print(np.mean(arr1))

print("\nMean of Second Array:")
print(np.mean(arr2))


Mean of First Array:
35.0

Mean of Second Array:
40.0


In [7]:
# Calculate Median
print("\nMedian of First Array:")
print(np.median(arr1))

print("\nMedian of Second Array:")
print(np.median(arr2))


Median of First Array:
35.0

Median of Second Array:
40.0


In [8]:
# Calculate Mode
print("\nMode of First Array:")
print(stats.mode(arr1, axis=None))

print("\nMode of Second Array:")
print(stats.mode(arr2, axis=None))


Mode of First Array:
ModeResult(mode=np.int64(10), count=np.int64(1))

Mode of Second Array:
ModeResult(mode=np.int64(15), count=np.int64(1))
