In [2]:
# 1) Combining a one and a two-dimensional NumPy Array 

In [1]:
import pandas as pd
import numpy as np


In [8]:


# Create first NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Create second NumPy array
arr1 = np.array([40, 50, 60, 70])

# Print first array
print(arr)

# Print second array
print(arr1)

# Combine both arrays using concatenate()
# axis=0 joins arrays in a single row (for 1D arrays)
result1 = np.concatenate((arr, arr1), axis=0)

# Print the combined array
print(result1)

[1 2 3 4 5]
[40 50 60 70]
[ 1  2  3  4  5 40 50 60 70]


In [9]:

# Create first 2D array
a = np.array([
    [10, 20, 30, 40],
    [45, 65, 85, 75]
])

# Create second 2D array
b = np.array([
    [100, 120, 130, 450],
    [145, 265, 385, 475]
])

# Print first array
print(a)

# Print second array
print(b)

# Combine arrays vertically (row-wise)
# axis=0 adds rows of b below rows of a
result2 = np.concatenate((a, b), axis=0)

# Print combined array
print(result2)

[[10 20 30 40]
 [45 65 85 75]]
[[100 120 130 450]
 [145 265 385 475]]
[[ 10  20  30  40]
 [ 45  65  85  75]
 [100 120 130 450]
 [145 265 385 475]]
