In [1]:
# 4) Replace negative value with zero in numpy array using replace



In [2]:
import numpy as np

In [3]:
# Replace negative values with 0 in NumPy array

import numpy as np

# Create array
arr = np.array([

    [6, -8, 73, -110],

    [5, -2, 0, 94]

])

print("Original Array:\n")

print(arr)


# Replace negative values with 0
arr[arr < 0] = 0

print("\nUpdated Array:\n")

print(arr)

Original Array:

[[   6   -8   73 -110]
 [   5   -2    0   94]]

Updated Array:

[[ 6  0 73  0]
 [ 5  0  0 94]]
