In [ ]:
# 1) Replace Nan with 0 and 
# Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]]

In [6]:
import pandas as pd
import numpy as np


In [9]:
import numpy as np

# Create 2D array
arr = np.array([

    [6, -8, 73, -110],

    [np.nan, -8, 0, 94]

])

print("Original Array:\n")

print(arr)


# Replace NaN with 0
new_arr = np.nan_to_num(arr, nan=0)

print("\nAfter Replacing NaN with 0:\n")

print(new_arr)


# Interchange rows and columns (Transpose)
transpose_arr = new_arr.T

print("\nAfter Interchanging Rows and Columns:\n")

print(transpose_arr)


Original Array:

[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

After Replacing NaN with 0:

[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

After Interchanging Rows and Columns:

[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]
