In [1]:
# 3) Replace NaN values with average of columns 

In [5]:
import numpy as np

# Create 2D array
arr = np.array([

    [6, -8, 73, -110],

    [np.nan, -8, 0, 94]

])

print("Original Array:\n")

print(arr)


# Calculate column-wise mean ignoring NaN
col_mean = np.nanmean(arr, axis=0)

print("\nColumn Means:\n")

print(col_mean)


# Find indices of NaN values
inds = np.where(np.isnan(arr))


# Replace NaN with corresponding column mean
arr[inds] = np.take(col_mean, inds[1])

print("\nAfter Replacing NaN with Column Average:\n")

print(arr)

Original Array:

[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

Column Means:

[ 6.  -8.  36.5 -8. ]

After Replacing NaN with Column Average:

[[   6.   -8.   73. -110.]
 [   6.   -8.    0.   94.]]
